/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package hiveSerdeCLI

import kotlinx.cli.ArgParser
import kotlinx.cli.ArgType
import kotlinx.cli.required
import org.apache.hadoop.hive.serde2.OpenCSVSerde
import java.util.Properties
import org.apache.hadoop.hive.serde.serdeConstants
import org.apache.hadoop.io.Text
import java.io.File

class App {
    fun deserialize(columns: String, columnTypes: String, fileName: String) {
        val csv = OpenCSVSerde()
        val props = Properties()
        props.setProperty(serdeConstants.LIST_COLUMNS, columns)
        props.setProperty(serdeConstants.LIST_COLUMN_TYPES, columnTypes)
        csv.initialize(null, props, null)
        val text = File(fileName).readText()
        val `in` = Text(text)
        val row = csv.deserialize(`in`) as List<*>
        println(row)
        println(row.size)
    }
}

fun main(args: Array<String>) {
    val parser = ArgParser("HiveSerdeCLI")
    val columns by parser.option(ArgType.String, shortName = "c", description = "Columns").required()
    val columnTypes by parser.option(ArgType.String, shortName = "ct", description = "Columns Types").required()
    val fileName by parser.option(ArgType.String, shortName = "f", description = "File Name").required()
    parser.parse(args)

    App().deserialize(columns, columnTypes, fileName)
}
