/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package hiveSerdeCLI

import org.apache.hadoop.hive.serde2.OpenCSVSerde
import java.util.Properties
import org.apache.hadoop.hive.serde.serdeConstants
import org.apache.hadoop.io.Text
import java.io.File

class App {
    fun deserialize() {
        val csv = OpenCSVSerde()
        val props = Properties()
        props.setProperty(serdeConstants.LIST_COLUMNS, "a,b,c")
        props.setProperty(serdeConstants.LIST_COLUMN_TYPES, "string,string,string")
        csv.initialize(null, props, null)
        val fileName = "test.csv"
        val text = File(fileName).readText()
        val `in` = Text(text)
        val row = csv.deserialize(`in`) as List<*>
        println(row)
        println(row.size)
    }
}

fun main() {
    App().deserialize()
}
